version: '3.3'

services:
    db:
        image: postgres
        restart: always
        networks:
          - back
        environment:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
        volumes:
          - dbdata:/var/lib/postgresql/data
    sonar:
        image: sonarqube
        ports:
          - 9000:9000
        networks:
          - front
          - back
        environment:
          SONARQUBE_JDBC_USERNAME: sonar
          SONARQUBE_JDBC_PASSWORD: sonar
          SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar 

volumes:
    dbdata:

networks:
  front:
  back:
